# Generated by Django 4.2.1 on 2023-06-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0008_alter_userlogin_ip_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLogin',
            new_name='UserLoginRecords',
        ),
        migrations.AlterModelTable(
            name='userloginrecords',
            table='user_login_records',
        ),
    ]
