# Generated by Django 4.2.2 on 2023-06-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0012_alter_blockeduser_options_friend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['-friendship_at']},
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('friend', 'user')},
        ),
        migrations.AlterModelTable(
            name='friend',
            table='user_friend',
        ),
    ]
