# Generated by Django 4.2.2 on 2023-06-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0014_alter_blockeduser_blocked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_friend_requests',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_messages',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='share_info',
            field=models.CharField(blank=True, choices=[('public', 'Herkes'), ('registered', 'Kayıtlı Üyeler')], default='public', max_length=20),
        ),
    ]
