# Generated by Django 4.2.2 on 2023-06-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0015_profile_allow_friend_requests_profile_allow_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allow_messages',
            field=models.CharField(blank=True, choices=[('public', 'Herkes'), ('registered', 'Kayıtlı Üyeler')], default='public', max_length=20),
        ),
    ]
