# Generated by Django 4.2.2 on 2023-06-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0016_alter_profile_allow_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allow_messages',
            field=models.CharField(blank=True, choices=[('public', 'Herkes'), ('registered', 'Kayıtlı Üyeler'), ('friends', 'Sadece Arkadaşlarım')], default='public', max_length=20),
        ),
    ]
