export const TopicTags = [
   {
      name: 'Javascript',
      description: 'Javascript ve diğer dalları hakkında sorularınız için.',
      total_Q: 1024,
      new_total_Q: 10,
      created_at: '10.07.2023 15:00',
   },
   {
      name: 'Python',
      description: 'Python ve diğer dalları hakkında sorularınız için.',
      total_Q: 1500,
      new_total_Q: 10,
      created_at: '09.07.2023 15:00',
   },
   {
      name: 'Javascript',
      description: 'Javascript ve diğer dalları hakkında sorularınız için.',
      total_Q: 1024,
      new_total_Q: 10,
      created_at: '10.07.2023 15:00',
   },
   {
      name: 'Python',
      description: 'Python ve diğer dalları hakkında sorularınız için.',
      total_Q: 1500,
      new_total_Q: 10,
      created_at: '09.07.2023 15:00',
   },
   {
      name: 'Javascript',
      description: 'Javascript ve diğer dalları hakkında sorularınız için.',
      total_Q: 1024,
      new_total_Q: 10,
      created_at: '10.07.2023 15:00',
   },
   {
      name: 'Python',
      description: 'Python ve diğer dalları hakkında sorularınız için.',
      total_Q: 1500,
      new_total_Q: 10,
      created_at: '09.07.2023 15:00',
   },
   {
      name: 'Javascript',
      description: 'Javascript ve diğer dalları hakkında sorularınız için.',
      total_Q: 1024,
      new_total_Q: 10,
      created_at: '10.07.2023 15:00',
   },
   {
      name: 'Python',
      description: 'Python ve diğer dalları hakkında sorularınız için.',
      total_Q: 1500,
      new_total_Q: 10,
      created_at: '09.07.2023 15:00',
   },
];
