# Generated by Django 4.2.2 on 2023-07-13 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('synonym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic_tags.tag')),
            ],
            options={
                'verbose_name': 'Konu/Soru Etiketi',
                'verbose_name_plural': 'Konu/Soru Etiketleri',
                'db_table': 'topic_tag',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('is_accepted', models.BooleanField(blank=True, default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topic_tags.tag')),
            ],
            options={
                'verbose_name': 'Etiket Eşanlamı',
                'verbose_name_plural': 'Etiket Eşanlamları',
                'db_table': 'topic_tag_synonym',
            },
        ),
    ]
