# Generated by Django 4.2.2 on 2023-07-10 23:11

import core.topic_tags.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_tags', '0002_alter_tag_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='synonyms',
            field=core.topic_tags.models.SynonymousTagField(blank=True, null=True, unique=True),
        ),
    ]
