# Generated by Django 4.2.1 on 2023-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob_privacy',
            field=models.CharField(choices=[('none', 'Hiçbir Şeyi Gösterme'), ('age', 'Sadece Yaş'), ('month_day', 'Ay ve Gün'), ('year_age', 'Yaş ve Yıl')], default='age', max_length=20),
        ),
    ]
