# Generated by Django 4.2 on 2023-04-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='core_user',
        ),
    ]
