# Generated by Django 4.2 on 2023-05-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Çevrimiçi'), ('OFFLINE', 'Çevrimdışı')], default='OFFLINE', max_length=20),
        ),
    ]
