# Generated by Django 4.2.1 on 2023-06-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_remove_profile_age_profile_dob_profile_dob_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob_privacy',
            field=models.CharField(choices=[('none', 'Hiçbir Şeyi Gösterme'), ('age', 'Sadece Yaş'), ('month_day', 'Ay ve Gün'), ('show', 'Her Şeyi Göster')], default='age', max_length=20),
        ),
    ]
