# Generated by Django 4.2.1 on 2023-06-03 16:52

import core.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to=core.user.models.get_upload_path),
        ),
    ]
