# Generated by Django 4.2 on 2023-04-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
