# Generated by Django 4.2 on 2023-05-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_accountactivation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountactivation',
            table='user_activation_code',
        ),
    ]
