# Generated by Django 4.2 on 2023-05-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
