# Generated by Django 4.2.1 on 2023-06-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0006_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='browser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='device',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
