# Generated by Django 4.2.1 on 2023-06-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0007_userlogin_browser_userlogin_os_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
