# Generated by Django 4.2.1 on 2023-06-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0010_blockeduser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blockeduser',
            table='user_blockeduser',
        ),
    ]
